FROM ruby:3.4.1

LABEL maintainer="cayala.w@gmail.com"

# Allow apt to work with https-based sources
RUN apt-get update -yqq && \
apt-get install -yqq --no-install-recommends apt-transport-https nodejs

COPY Gemfile* /usr/src/app/
WORKDIR /usr/src/app
ENV BUNDLE_PATH /gems
RUN bundle install

COPY . /usr/src/app/

ENTRYPOINT ["./docker-entrypoint.sh"]
CMD ["bin/rails", "s", "-b", "0.0.0.0"]
